media: src/img
content:
  - name: posts
    label: Posts
    type: collection
    path: src/posts
    fields:
      - { name: title, label: Title, type: string }
      - { name: date, label: Date, type: date, options: { format: YYYY-MM-DD } }
      - { name: img, label: Image, type: image }
      - { name: summary, label: Description, type: string, options: { maxlength:160 } }
      - { name: gif, label: GIF, type: image, options: { extensions: [ gif ] } }
      - { name: tags, label: Tags, type: string }
      - { name: body, label: Body, type: code }
  - name: news
    label: News
    type: collection
    path: src/news
    fields:
      - { name: title, label: Title, type: string }
      - { name: date, label: Date, type: date, options: { format: YYYY-MM-DD } }
      - { name: summary, label: Description, type: string, options: { maxlength:160 } }
      - { name: img, label: Image, type: image }
      - { name: body, label: Body, type: code }